name: Deploy HerZog v3 to Digital Ocean

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run basic syntax check
      run: |
        python -m py_compile main_bot.py
        python -m py_compile src/main_pipeline.py
        
    - name: Test imports
      run: |
        python -c "from src.shared.gemini_client import GeminiClient"
        python -c "from src.ai_agents.work_packager import WorkPackager"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        
    - name: Deploy to Digital Ocean
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.DO_DROPLET_IP }} << 'EOF'
          # Переходим в папку проекта или создаем её
          cd /opt || mkdir -p /opt
          
          # Останавливаем старый контейнер
          docker-compose -f herzog/docker-compose.yml down || true
          
          # Клонируем или обновляем репозиторий
          if [ -d "herzog" ]; then
            cd herzog
            git pull origin main
          else
            git clone https://github.com/AyanbekDos/HerZog.git herzog
            cd herzog
          fi
          
          # Создаем .env файл из секретов
          cat > .env << EOL
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          ENVIRONMENT=production
          LOG_LEVEL=INFO
          EOL
          
          # Собираем и запускаем новый контейнер
          docker-compose build --no-cache
          docker-compose up -d
          
          # Очищаем старые образы
          docker image prune -f
          
          echo "✅ HerZog v3 успешно развернут!"
        EOF